{{ if .Values.submarine.traefik.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.submarine.server.name}}-ingress
  namespace: {{ .Release.namespace }}

spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.submarine.server.name }}
              servicePort: {{ .Values.submarine.server.servicePort }}
{{ end }}
