name: python-sdk

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        python-version: [3.6, 3.7]
        tf-version: [1.14.0, 1.15.0]
      fail-fast: false
    env:
      PYTHON: ${{ matrix.python }}
    steps:
      - name: Checkout project
      - uses: actions/checkout@v1
      - name: Setup python environment
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir tensorflow==${{ matrix.tf-version }}
          pip install --no-cache-dir torch==1.5.0
          pip install --no-cache-dir ./submarine-sdk/pysubmarine/.
          pip install -r ./submarine-sdk/pysubmarine/github-actions/test-requirements.txt
          pip install -r ./submarine-sdk/pysubmarine/github-actions/lint-requirements.txt
      - name: Check python sdk code style
        run: |
          ./submarine-sdk/pysubmarine/github-actions/lint.sh
      - name: Run unit test
        run: |
          pytest --cov=submarine -vs -m "not e2e"
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Set up Maven 3.6.3
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3
      - name: Check version
        run: |
          mvn --version
          java -version
      - name: Build submarine
        run: mvn clean package -DskipTests